[package]
name = "shadow-protocol"
version = "0.1.0"
description = "Shadow Protocol - Privacy-Preserving Auction Platform"
edition = "2021"
rust-version = "1.75.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "shadow_protocol"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.1" }
# TODO: Fix version conflicts with Arcium packages
# arcium-anchor = { version = "0.1.45" }
# arcium-client = { version = "0.1.45" }
# arcium-macros = { version = "0.1.45" }

[dev-dependencies]
solana-sdk = "2.3.1"
solana-program-test = "2.3.1"