[package]
name = "shadow-protocol-confidential"
version = "0.1.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
shadow_protocol = "ShadowProtocol11111111111111111111111111111"

[programs.devnet]
shadow_protocol = "ShadowProtocol11111111111111111111111111111"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"

[workspace]
members = [
    "confidential-ixs"
]